'use client';

import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { toast } from 'sonner';

type Session = { answer: (options?: { video?: boolean }) => Promise<unknown>; reject: () => void; hangup: () => void; mute: () => void; unmute: () => void; blindTransfer: (number: string) => void; attendedTransfer: (number: string) => void; audioToVideo: (allowNoneCamera?: boolean) => Promise<unknown>; videoToAudio: () => void; dtmf: (tone: string) => void; on: (event: string, listener: (payload: { stream?: MediaStream }) => void) => unknown; localStream?: MediaStream; remoteStream?: MediaStream };
type Phone = { start: () => unknown; call: (number: string, options?: { video?: boolean }) => Promise<unknown>; on: (event: string, listener: (payload: { session: Session }) => void) => unknown };
type State = { configured: boolean; connected: boolean; connecting: boolean; open: boolean; setOpen: (open: boolean) => void; status: string; incoming: Session | null; active: Session | null; localStream: MediaStream | null; remoteStream: MediaStream | null; call: (number: string, video?: boolean) => Promise<void>; answer: (video?: boolean) => Promise<void>; reject: () => void; hangup: () => void; mute: (value: boolean) => void; transfer: (number: string, attended?: boolean) => void; video: () => Promise<void>; dtmf: (tone: string) => void };
const TelephonyContext = createContext<State | null>(null);

export function TelephonyProvider({ children }: { children: ReactNode }) {
  const [configured, setConfigured] = useState(false); const [connected, setConnected] = useState(false); const [connecting, setConnecting] = useState(false); const [open, setOpen] = useState(false); const [status, setStatus] = useState(''); const [incoming, setIncoming] = useState<Session | null>(null); const [active, setActive] = useState<Session | null>(null); const [localStream, setLocalStream] = useState<MediaStream | null>(null); const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null);
  const phone = useRef<Phone | null>(null); const destroy = useRef<(() => void) | null>(null); const retry = useRef<ReturnType<typeof setTimeout> | null>(null); const live = useRef(true); const connectingRef = useRef(false);
  const connect = useCallback(async () => { if (connectingRef.current || !live.current) return; connectingRef.current = true; setConnecting(true); try { const r = await fetch('/api/telephony/yeastar/signature', { method: 'POST' }); const c = await r.json(); if (!r.ok) throw new Error(c.error); destroy.current?.(); const sdk = await import('ys-webrtc-sdk-core'); const op = await sdk.init({ username: c.extension, secret: c.secret, pbxURL: c.pbxUrl, reRegistryPhoneTimes: 999999 }); phone.current = op.phone as Phone; destroy.current = op.destroy; op.phone.on('registered', () => { setConnected(true); setStatus('Conectado'); }); op.phone.on('registrationFailed', () => { setConnected(false); setStatus('No se pudo registrar la extensión'); }); op.phone.on('disconnected', () => { setConnected(false); setStatus('Reconectando…'); if (live.current) retry.current = setTimeout(() => void connect(), 5000); }); op.phone.on('incoming', (p) => { setIncoming(p.session as Session); setOpen(true); setStatus('Llamada entrante'); toast.info('Llamada entrante'); }); op.phone.on('startSession', (p) => { const session = p.session as Session; setActive(session); setIncoming(null); setOpen(true); setStatus('Llamada en curso'); setLocalStream(session.localStream ?? null); setRemoteStream(session.remoteStream ?? null); session.on('streamAdded', event => { if (event.stream) setRemoteStream(event.stream); }); session.on('ended', () => { setActive(null); setLocalStream(null); setRemoteStream(null); setStatus('Llamada finalizada'); }); }); op.phone.on('deleteSession', () => { setActive(null); setIncoming(null); setLocalStream(null); setRemoteStream(null); setStatus('Llamada finalizada'); }); op.phone.start(); setConnected(true); } catch (error) { setConnected(false); setStatus(error instanceof Error ? error.message : 'Error de conexión'); } finally { connectingRef.current = false; setConnecting(false); } }, []);
  useEffect(() => { live.current = true; const close = () => destroy.current?.(); window.addEventListener('pagehide', close); fetch('/api/telephony/config').then(r => r.json()).then(x => { setConfigured(Boolean(x.config)); if (x.config) void connect(); }).catch(() => {}); return () => { live.current = false; window.removeEventListener('pagehide', close); if (retry.current) clearTimeout(retry.current); destroy.current?.(); }; }, [connect]);
  const value: State = { configured, connected, connecting, open, setOpen, status, incoming, active, localStream, remoteStream, call: async (n, video) => { setOpen(true); setStatus(`Llamando a ${n}…`); if (!phone.current) await connect(); await phone.current?.call(n, { video }); }, answer: async (video) => { if (incoming) await incoming.answer({ video }); }, reject: () => incoming?.reject(), hangup: () => active?.hangup() ?? incoming?.hangup(), mute: (v) => v ? active?.mute() : active?.unmute(), transfer: (n, attended) => { if (!active || !n.trim()) return; setStatus(attended ? `Consultando a ${n}…` : `Transfiriendo a ${n}…`); attended ? active.attendedTransfer(n) : active.blindTransfer(n); }, video: async () => { if (active) { setStatus('Solicitando vídeo…'); await active.audioToVideo(false); setLocalStream(active.localStream ?? null); setRemoteStream(active.remoteStream ?? null); } }, dtmf: t => active?.dtmf(t) };
  return <TelephonyContext.Provider value={value}>{children}</TelephonyContext.Provider>;
}
export function useTelephony() { const value = useContext(TelephonyContext); if (!value) throw new Error('useTelephony must be used inside TelephonyProvider'); return value; }
