'use client';

import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { toast } from 'sonner';

type Session = { answer: (options?: { video?: boolean }) => Promise<unknown>; reject: () => void; hangup: () => void; mute: () => void; unmute: () => void; blindTransfer: (number: string) => void; attendedTransfer: (number: string) => void; audioToVideo: () => Promise<unknown>; videoToAudio: () => void; dtmf: (tone: string) => void };
type Phone = { start: () => unknown; call: (number: string, options?: { video?: boolean }) => Promise<unknown>; on: (event: string, listener: (payload: { session: Session }) => void) => unknown };
type State = { configured: boolean; connected: boolean; connecting: boolean; incoming: Session | null; active: Session | null; call: (number: string, video?: boolean) => Promise<void>; answer: (video?: boolean) => Promise<void>; reject: () => void; hangup: () => void; mute: (value: boolean) => void; transfer: (number: string, attended?: boolean) => void; video: () => Promise<void>; dtmf: (tone: string) => void };
const TelephonyContext = createContext<State | null>(null);

export function TelephonyProvider({ children }: { children: ReactNode }) {
  const [configured, setConfigured] = useState(false); const [connected, setConnected] = useState(false); const [connecting, setConnecting] = useState(false); const [incoming, setIncoming] = useState<Session | null>(null); const [active, setActive] = useState<Session | null>(null);
  const phone = useRef<Phone | null>(null); const destroy = useRef<(() => void) | null>(null); const retry = useRef<ReturnType<typeof setTimeout> | null>(null); const live = useRef(true); const connectingRef = useRef(false);
  const connect = useCallback(async () => { if (connectingRef.current || !live.current) return; connectingRef.current = true; setConnecting(true); try { const r = await fetch('/api/telephony/yeastar/signature', { method: 'POST' }); const c = await r.json(); if (!r.ok) throw new Error(c.error); destroy.current?.(); const sdk = await import('ys-webrtc-sdk-core'); const op = await sdk.init({ username: c.extension, secret: c.secret, pbxURL: c.pbxUrl, reRegistryPhoneTimes: 999999 }); phone.current = op.phone as Phone; destroy.current = op.destroy; op.phone.on('registered', () => setConnected(true)); op.phone.on('registrationFailed', () => setConnected(false)); op.phone.on('disconnected', () => { setConnected(false); if (live.current) retry.current = setTimeout(() => void connect(), 5000); }); op.phone.on('incoming', (p) => { setIncoming(p.session as Session); toast.info('Llamada entrante'); }); op.phone.on('startSession', (p) => { setActive(p.session as Session); setIncoming(null); }); op.phone.on('deleteSession', () => { setActive(null); setIncoming(null); }); op.phone.start(); setConnected(true); } catch { setConnected(false); } finally { connectingRef.current = false; setConnecting(false); } }, []);
  useEffect(() => { live.current = true; fetch('/api/telephony/config').then(r => r.json()).then(x => { setConfigured(Boolean(x.config)); if (x.config) void connect(); }).catch(() => {}); return () => { live.current = false; if (retry.current) clearTimeout(retry.current); destroy.current?.(); }; }, [connect]);
  const value: State = { configured, connected, connecting, incoming, active, call: async (n, video) => { if (!phone.current) await connect(); await phone.current?.call(n, { video }); }, answer: async (video) => { if (incoming) await incoming.answer({ video }); }, reject: () => incoming?.reject(), hangup: () => active?.hangup() ?? incoming?.hangup(), mute: (v) => v ? active?.mute() : active?.unmute(), transfer: (n, attended) => attended ? active?.attendedTransfer(n) : active?.blindTransfer(n), video: async () => { if (active) await active.audioToVideo(); }, dtmf: t => active?.dtmf(t) };
  return <TelephonyContext.Provider value={value}>{children}</TelephonyContext.Provider>;
}
export function useTelephony() { const value = useContext(TelephonyContext); if (!value) throw new Error('useTelephony must be used inside TelephonyProvider'); return value; }
