-- CDR duration breakdown + call flow chronology, from Yeastar's
-- GET /openapi/v2.0/cdr/detail (see src/lib/telephony/yeastar-ai.ts).
ALTER TABLE public.yeastar_call_transcriptions
  ADD COLUMN IF NOT EXISTS routing_duration_seconds INTEGER,
  ADD COLUMN IF NOT EXISTS handling_duration_seconds INTEGER,
  ADD COLUMN IF NOT EXISTS ring_duration_seconds INTEGER,
  ADD COLUMN IF NOT EXISTS hold_duration_seconds INTEGER,
  ADD COLUMN IF NOT EXISTS talk_duration_seconds INTEGER,
  ADD COLUMN IF NOT EXISTS disconnected_by TEXT,
  ADD COLUMN IF NOT EXISTS timeline JSONB NOT NULL DEFAULT '[]'::jsonb;

-- The call summary is now generated by NexoOmni's own AI from the
-- transcript, not fetched from Yeastar's getaisummary.
ALTER TABLE ai_usage_log DROP CONSTRAINT IF EXISTS ai_usage_log_mode_check;
ALTER TABLE ai_usage_log
  ADD CONSTRAINT ai_usage_log_mode_check
  CHECK (mode IN ('auto_reply', 'draft', 'analysis', 'report', 'call_summary'));
